const Article = {
    // "Demo" : {
    //     title : "Demo",
    //     tag : ["html","css"],
    //     category : "front_end",
    //     img_content : "Demo",
    //     create_time : "2021/08/14",
    //     img_route : "/Content/img/Article/2021/08/Demo/Demo.jpg",
    //     img_place_name : "none",//圖片地名，none不顯示
    //     article_route:"/Article/2021/08/Demo.html",
    // },
    "HTML_script-tag_async&defer" : {
        title : "Html-script tag裡的async&defer用意",
        tag : ["html"],
        category : "front_end",
        create_time : "2022/02/02",
        img_route : "/Content/img/Article/2022/02/HTML_script-tag_async&defer/HTML_script-tag_async&defer.jpg",
        img_place_name : "苗栗雪霸國家公園",
        article_route:"/Article/2022/02/HTML_script-tag_async&defer.html",
    },
    "PHP_inculd&require" : {
        title : "PHP-inculd&require差別",
        tag : ["php"],
        category : "rear_end",
        create_time : "2021/10/09",
        img_content : "inculd</br>&</br>require",
        img_route : "/Content/img/Article/2021/10/PHP_inculd&require/PHP_inculd&require.png?v=1",
        img_place_name : "花蓮清水斷崖",
        article_route:"/Article/2021/10/PHP_inculd&require.html",
    },
    "CSS_Specificity" : {
        title : "CSS權重(CSS Specificity)",
        tag : ["css"],
        category : "front_end",
        create_time : "2021/09/19",
        img_content : "CSS</br>Specificity",
        img_route : "/Content/img/Article/2021/09/CSS_Specificity/CSS_Specificity.jpg?v=1",
        img_place_name : "花蓮",
        article_route:"/Article/2021/09/CSS_Specificity.html",
    },
};